# Generated by Django 6.1.1 on 2026-09-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='scans_processed/')),
                ('survey_id', models.CharField(default='SSS-2026-001', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_w', models.FloatField()),
                ('bbox_h', models.FloatField()),
                ('priority', models.CharField(default='LOW', max_length=20)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='api.scan')),
            ],
        ),
    ]
