from django.contrib import admin
from .models import Scan, Detection

@admin.register(Scan)
class ScanAdmin(admin.ModelAdmin):
    list_display = ('id', 'survey_id', 'uploaded_at', 'latitude', 'longitude')
    list_filter = ('survey_id', 'uploaded_at')
    search_fields = ('survey_id',)

    def has_add_permission(self, request):
        # Prevent manual creation; scans should be uploaded via API
        return False

@admin.register(Detection)
class DetectionAdmin(admin.ModelAdmin):
    list_display = ('id', 'scan', 'object_type', 'confidence', 'priority')
    list_filter = ('object_type', 'priority')
    search_fields = ('object_type',)

    def has_add_permission(self, request):
        # Prevent manual creation; detections should be generated by AI
        return False
